#!/bin/sh

set -e

# Determine absolute bin dir of this script
bin_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

if [ -z "${GIT_EXEC_PATH:-}" ]; then
  core_dir="$bin_dir/../libexec/git-core"
  if [ -d "$core_dir" ]; then
    GIT_EXEC_PATH=$(CDPATH= cd -- "$core_dir" && pwd -P)
    export GIT_EXEC_PATH
  fi
fi
exec "$bin_dir/git.original" "$@"
